import UiIcon from '@/components/ui-icon.vue';

const iconsList = [
    'addHouse',
    'address',
    'alarm',
    'alert',
    'apple',
    'arrowBackwards',
    'arrowDownCircle',
    'arrowDown',
    'arrowDownward',
    'arrowForward',
    'arrowLeftCircle',
    'arrowLeft',
    'arrowRightCircle',
    'arrowRight',
    'arrowUpCircle',
    'arrowUp',
    'arrowUpwards',
    'avatar',
    'bed',
    'bike',
    'boxStack',
    'brochureSent',
    'building',
    'bulb',
    'bus',
    'cadastralMap',
    'calculator',
    'calendar',
    'car',
    'certificate',
    'checkBold',
    'check',
    'checklist',
    'clock',
    'closeBold',
    'closeCircle',
    'close',
    'comment',
    'complex',
    'contentPlatform',
    'creditcard',
    'crop',
    'crown',
    'daycare',
    'dice',
    'document',
    'door',
    'dotsHorizontal',
    'download',
    'emoExcited',
    'emoHappy',
    'emoSad',
    'energy',
    'error',
    'euro',
    'exit',
    'external',
    'eye',
    'facebook',
    'ferry',
    'filter',
    'filters',
    'floorplan',
    'forSale',
    'fullscreenExit',
    'fullscreen',
    'garage',
    'gear',
    'google',
    'grip',
    'heartBorder',
    'heartFilledBorder',
    'heartFilled',
    'heartSemiFilled',
    'heart',
    'hide',
    'houseBold',
    'houseImag',
    'house',
    'houses',
    'images',
    'info',
    'infospot',
    'instagram',
    'international',
    'investor',
    'key',
    'link',
    'linkedin',
    'list',
    'locationPin',
    'location',
    'lock',
    'logoColorNvm',
    'logoColorVastgoedPro',
    'logoColorVbo',
    'logoColorVgm',
    'logoNvm',
    'logoVastgoedPro',
    'logoVbo',
    'logoVgm',
    'magazine',
    'mail',
    'makelaar',
    'megafono',
    'menu',
    'metro',
    'minusCircleInverted',
    'minus',
    'mortgage',
    'move',
    'navigate',
    'newHouse',
    'newspaper',
    'notFoundError',
    'notFoundHouse',
    'notFoundPage',
    'notFoundProperty',
    'notFound',
    'notes',
    'officeBold',
    'office',
    'online',
    'openHousePackage',
    'overview',
    'pencil',
    'phone',
    'photo360',
    'piggy',
    'pin',
    'pinterest',
    'plus',
    'printer',
    'promolabel',
    'question',
    'refresh',
    'removeBold',
    'remove',
    'robot',
    'school',
    'search',
    'sendBrochure',
    'share',
    'shield',
    'show',
    'smartphone',
    'sofa',
    'sold',
    'sort',
    'stairs',
    'starFilled',
    'star',
    'statsAverage',
    'statsBad',
    'statsGood',
    'success',
    'sun',
    'supermarket',
    'surface',
    'target',
    'thumbsDown',
    'thumbsUp',
    'tram',
    'trash',
    'tv',
    'twitter',
    'unauthorized',
    'upload',
    'userMenu',
    'user',
    'users',
    'video',
    'vr',
    'walk',
    'warning',
    'water',
    'website',
    'whatsapp',
    'youtube',
];

export default {
    title: 'Visual/Icon',
    component: UiIcon,
    argTypes: {
        icon: {
            control: {
                type: 'select',
                options: iconsList,
            },
        },
        size: {
            defaultValue: 'h-6 w-6',
            description: 'Change the size of the icon using tailwind classes',
            control: {
                type: 'text',
            },
        },
    },
};

const Template = (args, { argTypes }) => ({
    props: Object.keys(argTypes),
    components: { UiIcon },
    template: '<ui-icon :icon="icon" :size="size"></ui-icon>',
});

export const Icon = Template.bind({});
Icon.args = {
    icon: 'pin',
};
